### ISSUE TITLE
Razorpay Payment Integration and QR Code Payment Option for Donation Form

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/Slum-Scholars#3]
### Description
We want to integrate Razorpay payment gateway with the "Donate" button and also offer an alternative payment method via UPI QR code. Users should be able to either make a donation through Razorpay or scan the QR code for a direct UPI payment.

### Why is this feature important to you?
Providing both Razorpay integration and a UPI QR code gives donors flexibility in payment methods, thus improving their overall experience. This flexibility is likely to increase donations for Slum Scholar by catering to the preferences of different users.

### Solution wanted
1. **Razorpay Integration**: 
   - When a user fills out the donation form (Name, Email, Contact No., Amount, Message) and clicks on the "Pay" button, the Razorpay API should be triggered.
   - The Razorpay interface should open, allowing the user to complete the payment.
   - After a successful payment, a confirmation message or receipt should be displayed on the website.

2. **UPI QR Code**: 
   - Display the UPI QR code, which users can scan with their mobile devices to make a UPI payment.
   - Provide the UPI ID and bank details for transparency and to allow users to make manual payments if required.

### Additional context
- **Razorpay Integration**: The form should send relevant information (such as amount and user details) to the Razorpay API. A successful transaction should notify the system to update the donation database.
- **UPI QR Code**: The QR code will be static and linked to the UPI ID or bank account for easy payment. Ensure all bank details and IFSC code are visible.

### Example (with dummy details):
- **UPI ID**: `abcdquygfuhfoiwjvowir@upi`
- **Bank Account No**: `XXXXXXXXXSBI`
- **IFSC**: `BARB0VJMNRE` (5th character is zero)
- **Address**: XYZ Street, City, State, India
- **Email**: dummyemail@domain.com
- **Phone**: 9876543210

These details, along with the QR code, should be displayed clearly for transparency and ease of use.
Add relevant images in bg .(extra points)

**Comment by Vaishnavi1047** [comment]
@Codipk anyone have this issue?

**Comment by Codipk** [comment]
@Vaishnavi1047 U can work on this Try to do within the before the deadline
