### ISSUE TITLE
Make a Voluteer Form 

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/Slum-Scholars#4]
When user clicks on Apply now
<img width="425" alt="Screenshot 2024-10-25 at 7 11 37 PM" src="https://github.com/user-attachments/assets/e059bef7-4ea9-45f5-bc48-96bffabaa37a">

1. **Frontend Form**: 
   - Design a form that appears in a modal or on a new page when the user clicks "Join as Volunteer."
   - Fields:
     - Full Name
     - Current Address
     - Permanent Address
     - Aadhar Number
     - Phone Number
     - Activity (Dropdown: Marketing, Management, Teaching, Technical)
     - Date of Birth
     - Recent Qualification (Dropdown: 12th Pass, 10th Pass, Graduate, Post Graduate)
     - Other Qualifications
     - Email

2. **Backend Integration**:
   - Connect the form to your database to save user inputs. Use form validation to check each input (e.g., ensuring the phone number and Aadhar number are correct formats).
   - Use a secure method to handle sensitive data, especially for personal identifiers like Aadhar number.

3. **Confirmation**:
   - Optionally, add a confirmation or success message after submission to inform the user that their details have been saved.

**Comment by Codipk** [comment]
@aachintya strt working

**Comment by aachintya** [comment]
> @aachintya strt working

ok mam

**Comment by Codipk** [comment]
Also maintain the folder structures and as contact us backend was made do the post req of the form like this in the model make schema refer the contact us server
