### ISSUE TITLE
Make the UI of Admin Portal

### ISSUE THREAD

**Issue by Codipk** [ContriHUB/Slum-Scholars#6]
Create a UI for the admin portal to display all information about volunteers registered for Slum Scholar.An admin portal is essential for managing volunteer information efficiently. Having all volunteer details accessible in one interface will help administrators manage and track volunteer engagement seamlessly.

Solution which needed:
The UI should include the following:
A dashboard listing all volunteers with details like full name, address, Aadhar number, phone number, chosen activity, date of birth, qualification, and email.
List the volunteers sorted by recent.
Potentially include functions to update statuses(Pending/Checked).

Steps to do:
1. Inside App.js Make a route for Admin 
2. Create the Admin page in component/ui folder 
3. Make the UI and integrate with the backend

**Comment by Codipk** [comment]
@aachintya strt working!

**Comment by aachintya** [comment]
ok mam

**Comment by Vaishnavi1047** [comment]
@Codipk could u pls reject my request for this issue
